In [ ]:
## 00. Pytorch Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.Tensor()'

In [5]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [10]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [14]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [28]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6735, 0.5635, 0.3571, 0.0839],
        [0.1803, 0.2677, 0.2193, 0.3834],
        [0.8906, 0.8098, 0.2013, 0.3241]])

In [29]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244,244,3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get depracated message, use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the big errors in PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [4]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device = None, requires_grad = False)
# dtype = what datatype the tensor is
# device = what device is your tensor one
# requires_grad = whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype

torch.float32

In [5]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [6]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [12]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [13]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Geting information from tensors attributes

1. Tensors not right datatype -- to get datatype from a tensor, use `tensor.dtyp`
2. Tensors not right shape -- to get shape from a tensor, use `tensor.shape`
3. Tensors not on right device -- to get device from a tensor, use `tensor.device`

In [14]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2775, 0.9340, 0.1588, 0.9941],
        [0.3625, 0.4540, 0.7074, 0.6987],
        [0.3858, 0.1103, 0.7884, 0.3122]])

In [15]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [17]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2775, 0.9340, 0.1588, 0.9941],
        [0.3625, 0.4540, 0.7074, 0.6987],
        [0.3858, 0.1103, 0.7884, 0.3122]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [21]:
random_tensor = torch.rand(3,4)
random_tensor_64 = random_tensor.type(torch.int64)
random_tensor_64.dtype, random_tensor.dtype

(torch.int64, torch.float32)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [25]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [26]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [27]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication

In [28]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [29]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [32]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [33]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using trarnspose

A **transpose** switches the axes of dimensions of a given tensor

In [35]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min. max, mean, sum, etc. (tensor aggregation)

In [38]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: torch.mean() func requires a tensor of float32 datatype
torch.mean(x.type(torch.float32))

tensor(45.)

In [42]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [43]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position where min value occurs
x.argmin()

tensor(0)

In [45]:
# Find the position in tensor that has the max value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeeing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (wrapped) in a certain way

In [57]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of eachother
