In [ ]:
## 00. Pytorch Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.Tensor()'

In [5]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [10]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [14]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [28]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6735, 0.5635, 0.3571, 0.0839],
        [0.1803, 0.2677, 0.2193, 0.3834],
        [0.8906, 0.8098, 0.2013, 0.3241]])

In [29]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244,244,3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get depracated message, use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the big errors in PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [4]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device = None, requires_grad = False)
# dtype = what datatype the tensor is
# device = what device is your tensor one
# requires_grad = whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype

torch.float32

In [5]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [6]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [12]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [13]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Geting information from tensors attributes

1. Tensors not right datatype -- to get datatype from a tensor, use `tensor.dtyp`
2. Tensors not right shape -- to get shape from a tensor, use `tensor.shape`
3. Tensors not on right device -- to get device from a tensor, use `tensor.device`

In [14]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2775, 0.9340, 0.1588, 0.9941],
        [0.3625, 0.4540, 0.7074, 0.6987],
        [0.3858, 0.1103, 0.7884, 0.3122]])

In [15]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [17]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2775, 0.9340, 0.1588, 0.9941],
        [0.3625, 0.4540, 0.7074, 0.6987],
        [0.3858, 0.1103, 0.7884, 0.3122]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [21]:
random_tensor = torch.rand(3,4)
random_tensor_64 = random_tensor.type(torch.int64)
random_tensor_64.dtype, random_tensor.dtype

(torch.int64, torch.float32)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [25]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [26]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [27]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication

In [28]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [29]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [32]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [33]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using trarnspose

A **transpose** switches the axes of dimensions of a given tensor

In [35]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min. max, mean, sum, etc. (tensor aggregation)

In [38]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: torch.mean() func requires a tensor of float32 datatype
torch.mean(x.type(torch.float32))

tensor(45.)

In [42]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [43]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position where min value occurs
x.argmin()

tensor(0)

In [45]:
# Find the position in tensor that has the max value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeeing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (wrapped) in a certain way

In [57]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [59]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
# Stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [69]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [72]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNewe tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

Newe tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [74]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# Permute the original tensor to rearraange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # [color_chanels, height, width]

print(f"Previous shape: {x_original.shape}")
print(f"New shapee: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shapee: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [76]:
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [81]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [83]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [84]:
# Get all values of 0th and 1st dimensions but only index 1 of second dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [85]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [86]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [90]:
# Index on x to return 9
print(x[0,2,2])

# Index on x to return 3,6,9
print(x[0,:,2])

tensor(9)
tensor([3, 6, 9])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library
because of this, PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTroch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy to pytoch, pytorch reflects numpy's default datatype of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [93]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random) 

How a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of that data -> again -> again -> ...`

To reduce the randomness in neural entworks and PyTorch you use the concept of a **random seed**

What the random seed does is "flavour" the randomness

In [125]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4745, 0.4233, 0.5886, 0.1207],
        [0.0364, 0.1364, 0.5672, 0.4382],
        [0.8580, 0.5226, 0.3252, 0.4880]])
tensor([[0.2875, 0.8116, 0.7565, 0.3338],
        [0.3071, 0.9095, 0.5055, 0.3605],
        [0.5421, 0.4535, 0.4962, 0.5829]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [128]:
# Let's make some random but reproducible tensors

# Set random seed
RANDOM_SEED = 67
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.7380, 0.3646, 0.8673, 0.5464],
        [0.5885, 0.9785, 0.8875, 0.9903],
        [0.3595, 0.3245, 0.8871, 0.9991]])
tensor([[0.7380, 0.3646, 0.8673, 0.5464],
        [0.5885, 0.9785, 0.8875, 0.9903],
        [0.3595, 0.3245, 0.8871, 0.9991]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use your own GPU - takes a little bit of setup
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and acacess them

For 2, 3 Pytroch + GPU drivers (CUDA) takes setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

### 2. Check for GPU access with PyTorch

In [131]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

False

In [133]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [134]:
# Count number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [136]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [137]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [138]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [139]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & Extra-curriculum

See exercises here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [141]:
# Exercise 2
random_tensor_exercise = torch.rand(7,7)
random_tensor_exercise

tensor([[0.4763, 0.8621, 0.0743, 0.4259, 0.6866, 0.1963, 0.8095],
        [0.4213, 0.9940, 0.5490, 0.7117, 0.9492, 0.8565, 0.3673],
        [0.9702, 0.7095, 0.0099, 0.8118, 0.5898, 0.2141, 0.2108],
        [0.8591, 0.3247, 0.9777, 0.0017, 0.1263, 0.8813, 0.7555],
        [0.2781, 0.0729, 0.9519, 0.5461, 0.3806, 0.6294, 0.1874],
        [0.1534, 0.1167, 0.9848, 0.6505, 0.6763, 0.5585, 0.3210],
        [0.8792, 0.5248, 0.2051, 0.9235, 0.5487, 0.5465, 0.2468]])

In [142]:
# Exercise 3
random_tensor_exercise_2 = torch.rand(1,7)
torch.mm(random_tensor_exercise, random_tensor_exercise_2.T)

tensor([[1.4488],
        [2.4277],
        [1.6240],
        [2.0428],
        [1.5226],
        [1.5907],
        [1.8889]])

In [143]:
# Exercise 4
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

random_tensor_1 = torch.rand(7,7)
print(random_tensor_1)

random_tensor_2 = torch.rand(1,7)

torch.mm(random_tensor_1, random_tensor_2.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])