In [ ]:
## 00. Pytorch Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using 'torch.Tensor()'

In [5]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [10]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [14]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [28]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6735, 0.5635, 0.3571, 0.0839],
        [0.1803, 0.2677, 0.2193, 0.3834],
        [0.8906, 0.8098, 0.2013, 0.3241]])

In [29]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244,244,3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get depracated message, use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the big errors in PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device = None, requires_grad = False)
# dtype = what datatype the tensor is
# device = what device is your tensor one
# requires_grad = whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [50]:
float_32_tensor.dtype

torch.float32